server:
#项目端口号
  port: 8900
  servlet:
#项目的访问名称
    context-path: /user

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sq?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456